import streamlit as st
st.header("registeration form")
name=st.text_input("Enter name")
email=st.text_input("enter your email")
password=st.text_input("password",type="password")
message=st.text_area("message")
date=st.date_input("select date")
time=st.time_input("select time")
file=st.file_uploader("upload file")
play=st.checkbox("play")
read=st.checkbox("read")
w=st.checkbox("write")
gender=st.radio("gender",["male","female","other","not prefet to say"])
city=st.selectbox("city",["ahemdaabd","surat","rajkot"])
skill=st.multiselect("skill",["python","c++","java"])
age=st.slider("age",1,100)
size=st.select_slider("size",options=["s","m","l"])
if st.button("submit"):
    st.write("name:",name)
    st.write("email:",email)
    st.write("password:",password)
    st.write("message:",message)
    st.write("date:",date)
    st.write("time:",time)
    st.write("play:",play)
    st.write("read:",read)
    st.write("write",w)
    st.write("gender",gender)
    st.write("city",city)
    st.write("skill",skill)
    st.write("age",age)
    st.write("size",size)